### ISSUE TITLE
Unable to see transaction history

### ISSUE THREAD

**Issue by ayu1712** [subhodi/android-web3-lightwallet#1]
Where does all the transactions history are stored? I couldn't able to see the transaction history later. Is it stored ethereum blockchain or in wallet. I just wanted to see all transactions related to one address.

**Comment by subhodi** [comment]
@satan17 Transaction history is stored in the blockchain. There is no direct API to list transactions based on the address in the Web3 library. Refer [how-to-get-transactions-by-account-using-web3-js](https://ethereum.stackexchange.com/questions/8900/how-to-get-transactions-by-account-using-web3-js)
